# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      #- image:

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      
      - run: pwd
      - run: whoami
      - run: cd onsgroupproject
      - run: echo "creating database"
      - run: cd src/main/resources
      #- run: mysql -u root -p_t5rasdifouaorhto5qiXKCVJOUIE£JHTO < ons_database_creation.sql
         
      # Download and cache dependencies
      #- restore_cache:
          #keys:
            #- v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            #- v1-dependencies-

      - run: gradle dependencies

      #- save_cache:
          #paths:
            #- ~/.gradle
          #key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle build
      
      - run: gradle assemble
      
      - run: cd onsgroupproject/build/libs
      - run: java -jar onsgroupproject-0.0.1-SNAPSHOT.jar
